C_SOURCES = $(wildcard *.c)
HEADERS = $(wildcard *.h)

OBJ = ${C_SOURCES:.c=.o}

os-image: boot_kernel.bin kernel.bin
	cat $^ > os-img

#kernel.bin: enter_kernel.o ${OBJ} isrs.o
kernel.bin: enter_kernel.o ${OBJ}
	ld -melf_i386 -s -o kernel.bin -Ttext 0x1000 $^ --oformat=elf32-i386

%.o: %.c ${HEADERS}
	gcc -ffreestanding -m32 -s -c $< -o $@

%.o: %.asm
	nasm $< -f elf -o $@

%.bin: %.asm
	nasm $< -f bin -o $@

clean:
	rm *.o *.bin os-img
